const producto = [


    {    nombre: 'Mochila',
         colores: 'Rosa y celeste',
         tema: 'Paw Patrol',
         precio: '$ 230.000',
         imagen: 'paw',
         capacidad: '15 litros',
         material:'Poliester',
         altura: '30 cm',
         ancho: '20 cm',
         profundidad: '20 cm',  
         stock:'si', 
         codigo:'jkl-253', 

    },
  {      nombre: 'Mochila Espalda Footy Smile',
         colores: 'Rosa, azul y verde',
         tema: 'PaFooty Smile',
         precio: '$ 59.200',
         imagen: 'smile',
         capacidad: '12 litros',
         material:'Poliester y tela',
         altura: '46 cm',
         ancho: '30 cm',
         profundidad: '15 cm',  
         stock:'Sin Stock', 
         codigo:'MRC-1423', 

    },
    {      nombre: 'MochMochila Urbana Escolar Grande Quagliaila Espalda Footy Smile',
    colores: 'Gris, Negro y Azul',
    tema: 'Universitaria',
    precio: '$ 27.800',
    imagen: 'urbana',
    capacidad: '25 litros',
    material:'Nylon Impermeable',
    altura: '42 cm',
    ancho: '30 cm',
    profundidad: '17,5 cm',  
    stock:'Sin Stock', 
    codigo:'MCL-4450', 
},
{      nombre: 'Mochila Escolar Everlast',
colores: 'Gris y Azul',
tema: 'Everlast Deportiva',
precio: '$ 30.390',
imagen: 'everlast',
capacidad: '24 litros',
material:'Poliester',
altura: '45 cm',
ancho: '30 cm',
profundidad: '17 cm',  
stock:'si',
codigo:'LRP-7100', 
},


];

export default producto;