const productos = [


    {    nombre: 'Mochila',
         colores: 'Rosa y celeste',
         tema: 'Paw Patrol',
         precio: '$ 230.000',
         imagen: 'paw',
         capacidad: '15 litros',
         material:'Poliester',
         altura: '30 cm',
         ancho: '20 cm',
         profundidad: '20 cm',  
         detalle: 'Hacé que las niñas y niños disfruten de ir al colegio con todas sus cosas organizadas y con sus diseños preferidos.',
    },
  {      nombre: 'Mochila Espalda Footy Smile',
         colores: 'Rosa, azul y verde',
         tema: 'PaFooty Smile',
         precio: '$ 59.200',
         imagen: 'smile',
         capacidad: '12 litros',
         material:'Poliester y tela',
         altura: '46 cm',
         ancho: '30 cm',
         profundidad: '15 cm',  
    },
    {      nombre: 'MochMochila Urbana Escolar Grande Quagliaila Espalda Footy Smile',
    colores: 'Gris, Negro y Azul',
    tema: 'Universitaria',
    precio: '$ 27.800',
    imagen: 'urbana',
    capacidad: '25 litros',
    material:'Nylon Impermeable',
    altura: '42 cm',
    ancho: '30 cm',
    profundidad: '17,5 cm',  
},
{      nombre: 'Mochila Escolar Everlast',
colores: 'Gris y Azul',
tema: 'Everlast Deportiva',
precio: '$ 30.390',
imagen: 'everlast',
capacidad: '24 litros',
material:'Poliester',
altura: '45 cm',
ancho: '30 cm',
profundidad: '17 cm',  
},
{      nombre: 'Mochila Espalda Footy Smile',
colores: 'Rosa, azul y verde',
tema: 'PaFooty Smile',
precio: '$ 59.200',
imagen: 'smile',
capacidad: '12l',
material:'Poliester y tela',
altura: '46 cm',
ancho: '30 cm',
profundidad: '15 cm',  
},
   

];

export default productos;